### ISSUE TITLE
Getting white screen after yarn deploy

### ISSUE THREAD

**Issue by bchapin11** [metaplex-foundation/metaplex#1073]
I coded my Metaplex and did yarn, yarn bootstrap, yarn build, and then yarn deploy. Everything executed without error and my GitHub pages properly connected to my domain. However, when I click my domain, I just get a blank white screen for the website. Does anyone know how to fix this? Thanks

**Comment by kpysniak** [comment]
Can you share your domain?

**Comment by bchapin11** [comment]
http://deskdudesnft.com

**Comment by bchapin11** [comment]
http://deskdudesnft.com

**Comment by VeriumNFT** [comment]
Anyone have any solutions?

**Comment by VeriumNFT** [comment]
Hey @bchapin11 

I noticed your site still displays a blank white page. Did you configure your CNAME file properly before deploying? I was having the same issue because the domain was set to my Github page and not the custom domain. In your case, deskdudesnft.com. Try to update the file and make sure it's in your primary directory folder where you are creating the candy machine in. Build & deploy again after you update the file and see if you can see the connect wallet button.

It doesn't sound like you have any issues with your DNS because you said pages properly connected to your domain. Still double check to make sure you have also configured your CNAME record for your custom domain and point it to your Github pages for Metaplex as well replacing your custom domain A record IP address with the Github pages IP and adding the additional 3 IP address A records for Github pages:

185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

If you need any help with CSS styling your Metaplex minting site you can do it directly in your index.html file before re-deploying. Feel free to reach out to me on Discord @ **Verium#8115** and I'll be happy to discuss creating a simple style code for you to add into your index.html.

**Comment by rolandstudios** [comment]
I'm getting this issue as well
metaplex.rolandstudios.com

**Comment by 96seg96** [comment]
> I'm getting this issue as well metaplex.rolandstudios.com

Hey, I've been having this issue as well, but I see your site now works. How did you resolve it? Thank you!

**Comment by Techpidgin** [comment]
> > I'm getting this issue as well metaplex.rolandstudios.com
> 
> Hey, I've been having this issue as well, but I see your site now works. How did you resolve it? Thank you!

did you get a solution ? my CNAME is saved to git
