### ISSUE TITLE
I used a lower version of node it did'nt work

### ISSUE THREAD

**Issue by davidabuu** [metaplex-foundation/metaplex#1111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot (729)](https://user-images.githubusercontent.com/65656238/144714307-230b4be5-26f1-45f9-be8a-be4a916fe934.png)

**Comment by amritabithi** [comment]
Here is what worked for me - 

Use "nvm install 14.17.0" to install version v14.17.0, and then list all other versions using "nvm ls" and delete all other versions using "nvm uninstall <version>"  ...  do not include the letter 'v' in the version number.

Do this for BOTH your root user and for your regular user if you use both, so they each ONLY have version v14.17.0 installed by you.  You will want version 14.17.0 showing for both the normal user and root user when doing the command "node --version".

( Your root user may be using version v10.x as mine was, and when building under my normal user I was hitting dependencies I had to touch with the root user just to have permissions to build fully. )

**Comment by abrichr** [comment]
Thanks @amritabithi . Unfortunately this did not work for me on MacOS 12.0.1. Can you please share what version of npm and yarn you are using? Also, what OS are you on? I'm not able to run `nvm` via `sudo` (`command not found), and `sudo brew install nvm` results in `Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.`.

**Comment by amritabithi** [comment]
Yes I can only run node version v14.17.0 , and I must force my system to only use this version because my OS seems to want to revert to another version once in a while, so before I build I alawys check my node version.  I am using Ubuntu 20 linux desktop.

Before anything else I suggest installing the node version manager from here:  https://www.npmjs.com/package/n

Once installed, you can uninstall and install node version on your system easily, and tell your system what version to use.

Here are some commands to run:

# install the version of node we want, v14.17.0
`n install 14.17.0`

# run this command next which is basically the same as the above, but sets the active version also
`n 14.17.0`

I had a few versions installed at one point, and you can remove ones that you've installed by doing the following, note that on my system at least I cannot remove the system's "10.18.0" version that it comes with, so when I build I always make sure it is using the right version first, and if not I just run the "n 14.17.0" command again to have it use the right version.

# list currently installed node versions 
`n ls`

# using list output from the last command, delete the versions you don't want, this is optional
`n uninstall 17.0.0`

And again before I build I always run:
`node --version`

And if that does not return "v14.17.0" then I just run this again:
```
n install 14.17.0
n 14.17.0
```

Then run "node --version" and when you see v14.17.0 you should be able to complete the build with "yarn install".

MY OS INFO:
root@myhost:~# node --version
v14.17.0
root@myhost:~# npm --version
6.14.13
root@myhost:~# n --version
v8.0.1
root@myhost:~# yarn --version
1.22.17
root@myhost:~# nvm --version
0.34.0

**Comment by amritabithi** [comment]
( I am fixing my post there is some weird markup that showed up so I am cleaning it up )

**Comment by amritabithi** [comment]
Ok that should be readable now I had to remove some accidental formatting.

**Comment by amritabithi** [comment]
Here is a shorter version of those instructions:

`sudo wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash`

( now close your consnole and open a new one )

```
nvm install 14.17.0
nvm use 14.17.0
node --version
```
