### ISSUE TITLE
Can't create candy machine (SendTransactionError)

### ISSUE THREAD

**Issue by mahdinjim** [metaplex-foundation/metaplex#1120]
**Describe the bug**
After trying to execute the command "ts-node js/packages/cli/src/candy-machine-cli.ts create_candy_machine" we get the following error:

SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139

**Comment by amritabithi** [comment]
You may want to check that the creator wallet and the candy machine public key are funded with solana, if you are on the devnet still you can use this site to easily airdrop to wallets - https://solfaucet.com/ without the command line.  I also had to sign the candy machine creation transaction with my creator wallet not just any wallet.

Also, make sure that you do not have any fields in your json files if you are using those to create your NFTs, so if you have the "ticker" field in the json file for example, but it is an empty string, you will get an error.

Also, if you are on devnet use this command from the /metaplex/js/ folder:
solana config set --url devnet

( I had your same error and while I can't find exactly where I had it I think it was one of those three things that fixed it for me. )

**Comment by amritabithi** [comment]
( Also if you get an error while uploading or validating your NFTs, look for the file "devnet.json' and delete that file, then start over with uploading, validating and deploying.  My devnet.json file was located at  ~/.config/solana/devnet.json , and I would build from my home directory... if you build frmo another directory look beneat it for the devnet.json file. )

**Comment by rafaelescrich** [comment]
This ~/.config/solana/devnet.json is your key. Don't delete private keys if you don't know what you are doing.

**Comment by amritabithi** [comment]
Yes it is a good idea I think to output a separate copy of your wallet file called "id.json" or a name like that, so I always have two files at:
~./config/solana/devnet.json
~/config/solana/id.json

I also had to do this because when working with another popular candy machine script you actually write NFT data to the devnet.json file as you are configuring your NFT to be minted, and at one point I would be overwriting my devnet.json file repeatedly in testing, so I just always treat the devnet.json file as disposable and keep another backup in a safe place if I want to continue using that key.

**Comment by Khushhal23** [comment]
Also, add a --env mainnet-beta or devnet accordingly
