### ISSUE TITLE
Error in uploading assets

### ISSUE THREAD

**Issue by HAWKY-NFT** [metaplex-foundation/metaplex#1180]
npx ts-node js/packages/cli/src/candy-machine-cli.ts upload js/assets --env mainnet-beta --keypair /Users/user/Documents/NFTs/keypair.json

When i run the command on top I get the following error how do I fix it?

Must use import to load ES Module: /Users/user/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /Users/user/node_modules/node-fetch/src/index.js from /Users/user/Documents/NFTS/metaplex/js/packages/cli/src/candy-machine-cli.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/user/node_modules/node-fetch/package.json

**Comment by Khushhal23** [comment]
Actually the command ur using is wrong 

npx ts-node js/packages/cli/src/candy-machine-cli.ts upload js/assets --env mainnet-beta --keypair /Users/user/Documents/NFTs/keypair.json

Instead of this, use 

npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env mainnet-beta --keypair /Users/user/Documents/NFTs/keypair.json

And remember that u should have a assets folder with all ur images and json files in the metaplex folder
