### ISSUE TITLE
Royalties sharing with holders

### ISSUE THREAD

**Issue by Oubaluna** [metaplex-foundation/metaplex#1228]
**Is your feature request related to a problem? Please describe.**
Hi there, first all thank you metaplex for this nice work ! 

It's more a question than a real problem, I'm searching a lot and don't find anything related to this : 
how can I set rules for share part of the royalty with some holder that respect some condition ? 

**Describe alternatives you've considered**
Do it manually by asking address and see if they fullfill my condition then pay them 

Thank you very much if someone passed by and have a solution or a documentation I can learn from to do this ! Thank youuu !

**Comment by vdusart** [comment]
Hey @Oubaluna,
First of all I don't think you can change the array of people who receive royalties and even if it was possible, changing it for each NFT is not very efficient.
I think instead of asking them for their address you should go through all your NFTs, look at the owner. If he respects your conditions you add him in the list of holders. Then you share the royalties between each holder.

**Comment by Oubaluna** [comment]
Thank you so much for your reply ! Indeed, I think I need to dig into doing some snapshot and put holders that respect condition in a list of holder with whom I share my royalties ! Thanks again @vdusart !!
