### ISSUE TITLE
Unable to upload collection to candy machine

### ISSUE THREAD

**Issue by Voidsfury26** [metaplex-foundation/metaplex#1657]
Whenever I try to upload my collection, it goes well at first until it sends a server error 429 too many requests. The worst part is I actually get debited. I have done this a couple of times and have lost about 30$. How can I upload the NFTs (they are 250) and if not how can I recover my lost sol coins

**Comment by frosty214** [comment]
Did you try uploading and testing to the Devnet first? If not, I would recommend this so that you can work out kinks like this.

The 429 FetchError you are seeing is because the RPC node you are using in your `solana config get` is not able to upload the data. You need to use an endpoint node like one from [Genesys.go](https://genesysgo.com/) in your upload file. It would look something like this: 

`ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp config.json --rpc-url "https://psytrbhymqlkfrhudd.dev.genesysgo.net:8899/" -c example ./assets`

Go to the Genesys,go discord and their channel #rpc-endpoints channel for more info. Hope this helps!
