### ISSUE TITLE
[Bug]: 9 NFTs remaining but sold out

### ISSUE THREAD

**Issue by SamFordGH** [metaplex-foundation/metaplex#1763]
### Which package is this bug report for?

candy machine ui

### Issue description

When running the candy machine mint in browser, it says there are 9 NFTs remaining, however when you click the mint button it says sold out... 
<img width="445" alt="Screenshot 2022-02-10 at 11 47 40" src="https://user-images.githubusercontent.com/37219731/153402881-0607b6ff-a5f5-4e5a-ba66-46c0cd6ed462.png">

### Operating system

Mac

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by walter-grace** [comment]
I can confirm I was having this exact issue after updating the yarn and package.json files from the PR https://github.com/metaplex-foundation/metaplex/commit/d9a4bbde3cabef5c33f14c3a33d3d72c2938e045
My mint says it was sold out too

**Comment by BENMOU98** [comment]
The same issue

**Comment by bxuserx** [comment]
Same, it prevented my mint today.    :(

**Comment by stegaBOB** [comment]
I think the mint is actually sold out, but the UI hasn't updated fast enough. When you set your price that low and don't have a captcha, this is bound to happen.

**Comment by bxuserx** [comment]
So wait, 5 people have reported this issue. I have run the ts-node candy-machine-V2-cli.ts get_all_mint_addresses and can confirm that only the two I preminted have been minted, with 98 left unsold... and this issue is being closed?

I've ran 3 other candy machine mints. I can absolutely confirm this is a real issue and should not be closed.

**Comment by bxuserx** [comment]
comparing an old working candy machine with a new one, I think it has something to do with the migration from the 'BLOCKHASHES_PUBKEY' to the 'SLOT_HASHES_PUBKEY'. Went into Anchor web3 API but couldn't find these system variables.
<img width="1245" alt="Screen Shot 2022-02-15 at 12 08 18 AM" src="https://user-images.githubusercontent.com/86570251/153996715-f88678b6-62d3-434f-b08c-f49a49aed343.png">

**Comment by stegaBOB** [comment]
That could also be it. A recent change in Solana forced us to update the
candy machine.

**Comment by bxuserx** [comment]
Went back to an old version of metaplex, mint is now working. Pretty sure now that it's an issue with the slot hashing vs block hashing. Looks like anchor's API might not be matching the state correctly to query the number remaining, and is defaulting to a 'sold out' error message.
Since I use a .art extension on my site, I'm forced to use the project serum API instead of the default for candy machine. Perhaps additional latency in that API call is causing an async error in getting the slot hash state.
