### ISSUE TITLE
During gap time, cancelling bids disallowed.

### ISSUE THREAD

**Issue by bhgames** [metaplex-foundation/metaplex#177]

**Comment by murlokito** [comment]
Some context regarding a recent event that might have been impacted by this.

During a [Joe Sirc auction](https://joesirc.com/#/auction/A1RAzXaongsAGBb8kLDRaipHkwWbwSCUNmLaC272jYA7) I was the top bidder as the last few seconds approached, when [someone](https://solscan.io/account/DaiuhLjEVPirm7WcAZ3ntvB9BW3DuQRpbH1xVvwDFk5p) tried to "spoof" (or just bid and chickened out) a last second bid. With this last second bid, while interacting with the auction via Joe's own self-hosted UI everything looked broken for a couple minutes before I did an hard refresh. I was able to click the "Redeem Bid" button but the few transactions I did turned out to fail, a few links for those:
- [First](https://solscan.io/tx/278EagW1W3oPGEreRGbhfnCtLtViPxqAs4h3vcsTfEAnzTSbxX3rTHNW5T2zjm5KT5ohAJoyGydk9VvFw1m6fdYu)
- [Second](https://solscan.io/tx/4merLLSNN2fkzyVqkDKswnZarZCx2yGP7nL2GdZ2FKUogSaWBHbv4e5Uc7u91nvDBypdmggMNuZShzHsjL8MRPHs)
- [Third](https://solscan.io/tx/35qmsxSqFMaqUM9eGoaKyB7VwN692weNAw3yENNDz3F7mzsPvAXQhqoetXZXiGXqSqwsirMoxpFur6SYSxXyi67P)

It was after those three and another two or so that I hard refreshed the page and when it loaded again I saw the counter was still going but the UI still wouldn't let me do anything else besides click "Place bid", even though I was the highest bidder considering the other one was canceled. In this [tweet](https://twitter.com/hoaktrades/status/1421280876680331270) there's an image of what the UI looked like after I had 6 failed transactions to redeem the bid and hard refreshed the UI.

Here are also the links to the "spoofer" transactions which interacted with the auction:

- [Bid placement for 20 SOL](https://solscan.io/tx/3eUNhjscNP5qgpwWuocSQuWrSGaSc7bqfMn1X2SFUjhRck5WFsqvs3oph3MsCpCTmNijAW88Fzo8VVjvCvBMtxhB)
- [Another transaction which failed due to:](https://solscan.io/tx/uk1NCLVGRxsX8jLR1aVErR5uVpfKd86fKhPVgLMhfKjmAJeQkyZdY7THvcWYG1y6ufHUtGT3CLewCQpBNxmmW8c)
```
Program log: + Processing PlaceBid
Program log: Existing Bid is already active.
```
- [And another transaction ~2 seconds later which seems to have canceled the bid](https://solscan.io/tx/4rLEUbisGkJ8HAJQvQxFYPeivHbHj1816UnEBgUUgQhPAb9wHHiFWUR8DzCSV8W42HfMNfPHi925FBf3UpsaGuX7)
