### ISSUE TITLE
[Bug]: Init store not initializing

### ISSUE THREAD

**Issue by ninnjak** [metaplex-foundation/metaplex#1801]
### Which package is this bug report for?

storefront

### Issue description

1. clone repo
2. cd metaplex/js
3. yarn install && yarn bootstrap && yarn build
4. yarn start
5. navigate to localhost:3000
6. connect wallet (devnet)
7. click "Init store"
8. observe infinite loading spinner with uncaught timeout

### Command

```shell
$ git clone https://github.com/metaplex-foundation/metaplex.git
$ cd metaplex/js
$ yarn install && yarn bootstrap && yarn build
$ yarn start
```

### Relevant log output

```shell
breadcrumbs.ts:111 Signed txns length 2 vs handed in length 2
breadcrumbs.ts:111 Started awaiting confirmation for YqTG41ASduvvArb3eGcY68Xj7hT9g46pn4jRognNxE1kQD439bDSFKkhPDbh9xHRgQakWqJP2mpvexaKoDyKdaq
breadcrumbs.ts:111 Rejecting for timeout...
helpers.ts:109 Uncaught {timeout: true}
  sentryWrapped @ helpers.ts:109
```

### Operating system

MacOS

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Try running it a few times and refreshing. I just got it to work on my end but it took 2 tries.

**Comment by nullmicgo** [comment]
i am having the same problem.
Any clues to resolve it?

**Comment by gpaluk** [comment]
> Try running it a few times and refreshing. I just got it to work on my end but it took 2 tries.

Couldn't get things working with this 'strategy'.

**Comment by SamSLSystem** [comment]
Same here....

**Comment by facetimer** [comment]
Same too  ...

**Comment by cryptorrivem** [comment]
If you're trying to run it on devnet, then wait for the Init button to show, and go change the network in the ⚙️ icon

**Comment by cryptorrivem** [comment]
Then try several times initializing, and it'll work

**Comment by THEOGHANGMAN** [comment]
any solve for this?

**Comment by facetimer** [comment]
> If you're trying to run it on devnet, then wait for the Init button to show, and go change the network in the ⚙️ icon

I'am on the mainet. i'am able to mint, sell my nft. 
But the first loading page takes 5 minutes....
Did you resolve it ?

Thank you

**Comment by stegaBOB** [comment]
If you want your storefront to be faster and/or to initialize properly, you can try using Holaplex in the meantime. Its super easy to use and its quite fast. We have a solution hopefully coming relatively soon that will make all the problems go away. Closing this issue for now.

**Comment by gpaluk** [comment]
@stegaBOB  'Having a solution coming' isn't a solution to THIS issue, especially when told a solution is coming without any 🌈actually information🌈  or that this codebase may be part other peoples projects - Can we at least get an ETA on the *thing* that might be a solution under, probably a narrow use case? And can the ticket be reopened until that time given that this bug still clearly exists and therefore shouldn't be closed? Thank you

**Comment by stegaBOB** [comment]
The entire storefront is being revamped. That's going to be the solution to this.

**Comment by gpaluk** [comment]
@stegaBOB  Ok, well thanks for the response but our case is quite different. We are actually lifting functions in order to create a lazy minting flow (which doesn't seem to have been considered, please correct me if I'm wrong here). For us, we'd much rather be interacting with an API that takes lazy minting into consideration, and supports all of the great features of metaplex/holoplex however we won't know if it's a solution for us until it drops. This is preventing my own project from going live too, so what is the best way to track the progress of the upcoming solution? Regards.

**Comment by gpaluk** [comment]
> If you want to interact with our programs not using the storefront, you should probably be using our SDKs in some form or another. The current storefront functions are quite... old and not great to be honest. You shouldn't really be using those methods.

Sure thing, but we also experience similar issues using the SDK, in fact we've probably tried around 4 different paths, all of which were unsuccessful. Perhaps there is a way that we can connect rather than me polute this thread? hello@plugin.io - we'd really appreciate the support to figure out this flow and then I'd be most happy to create a comprehensive blog post about how one might resolve this, the upcoming features, contribute to the codebase, and create a guide about how to work with the SDKs.

**Comment by gpaluk** [comment]
Hi @stegaBOB - We have requested information numerous times and been told that the JS SDK is very close to release and to hold fire with that. I didn't get any contact from my message above so given that this is 26 days later, I do wonder if you have a JS SDK release date at this point?
