### ISSUE TITLE
[Bug]: Can someone help me!

### ISSUE THREAD

**Issue by ddcc3388** [metaplex-foundation/metaplex#1961]
### Which package is this bug report for?

candy machine cli

### Issue description

I ran the command stated below. I have also funded my wallet with 20 sold. After running "upload" it always says not enough funds.

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example \
    ./assets
```

### Relevant log output

```shell
Saved bundle upload result to cache.
Computed Bundle range, including 390 file pair(s) totaling 1.734MB.
Processing file groups...
Progress: [████████████████████████████████████████] 100% | 390/390
Uploading bundle via Bundlr... in multiple transactions
0.000501652 SOL to upload 1.873MB with buffer. Sending fund txn...
Successfully funded Arweave Bundler, starting upload
Progress: [█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░] 32% | 382/1170
Could not complete Bundlr tx upload successfully, exiting due to:  Error: Not enough funds to send data
```

### Operating system

Mac M1

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by phillmorgan28** [comment]
We're also getting this same error, updated a previous ticket here
https://github.com/metaplex-foundation/metaplex/issues/1885#issuecomment-1067862064

**Comment by phillmorgan28** [comment]
Retried moments ago on mainnet-beta and still have the same issue. 1.5 SOL available in wallet.

Computed Bundle range, including 3333 file pair(s) totaling 14.871MB.
Processing file groups...
Progress: [████████████████████████████████████████] 100% | 3333/3333
Uploading bundle via Bundlr... in multiple transactions
0.00533355 SOL to upload 16.909MB with buffer. Sending fund txn...
Successfully funded Arweave Bundler, starting upload
Progress: [██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░] 34% | 3461/9999
Could not complete Bundlr tx upload successfully, exiting due to:  Error: Not enough funds to send data
    at NodeUploader.dataItemUploader (/home/phill/metaplex/js/node_modules/@bundlr-network/client/build/common/upload.js:43:23)
    
Seems to be some discrepancy between estimated and actual cost??

**Comment by stegaBOB** [comment]
Should be fixed now
