### ISSUE TITLE
[Bug]: Unknown Collection

### ISSUE THREAD

**Issue by angushk** [metaplex-foundation/metaplex#2089]
### Which package is this bug report for?

candy machine cli

### Issue description

I've go through the complete steps to build NFT and success to mint on the UI site, however my NFT displaying on mobile phantom is Unknown Collection, is it a bit of candy machine or phantom? Or my set_collection command type wrongly?

ps: i didn't type -m as this is an optional cmd and I don't know type I should type here (seems not wallet address nor Candy machine address).

### Command

```shell
ts-node candy-machine-v2-cli.ts set_collection -e mainnet-beta -k xxxxxxxxxxx.json -c xxxxxxxx
```

### Operating system

Win10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by spreadcharm** [comment]
Is your Desktop browser phantom working properly?
If so, it's mobile phantom's problem, I think.
And even it's not working on both of mobile & desktop, I think it's due to the phantom problem, not candymachine.
Since you define metadata in json file together with nft images, and candymachine just upload it as you inputted.
If the candymachine has a prblem, it wouldn't be uploaded rather than displaying "Unknown collection" after successful upload.
