### ISSUE TITLE
Adding option to mint multiple tokens at once? 

### ISSUE THREAD

**Issue by WilliamRT95** [metaplex-foundation/metaplex#363]
Will be great almost necessary to let people mint multiple tokens if they wanted to. As far as I'm concerned we only have the option of "mint_one_token".

Thank you!

**Comment by AlexLeung** [comment]
In theory we should be able to create one transaction with multiple calls to mint one token, right?

**Comment by WilliamRT95** [comment]
As far as Im concerned you have to implement "const signedTxns = await wallet.signAllTransactions(unsignedTxns);" metaplex already has in their marketplace. Will be great if they can implement that to use outside their marketplace. For now we are stuck with mint_one_token, unless you implement it yourself.

**Comment by AcoustiCoder** [comment]
how can i use mint_one_token command? sorry about this question. im asking because i dont know anything about react.

**Comment by kevinfaveri** [comment]
Hello guys, I've just implemented it in my repo (mintMultipleToken, which receives a param called quantity). It will be multiple transactions but the user will only be prompted once. Check it here: https://github.com/kevinfaveri/solana-candy-factory/blob/main/src/utils/candy-machine.ts#L332

**Comment by AlexLeung** [comment]
> Hello guys, I've just implemented it in my repo (mintMultipleToken, which receives a param called quantity). It will be multiple transactions but the user will only be prompted once. Check it here: https://github.com/kevinfaveri/solana-candy-factory/blob/main/src/utils/candy-machine.ts#L332

Is the whole thing atomic? Meaning it will either all succeed or all fails? Are there scenarios where some fail and others do not? If so how do you track that? This looks promising.

**Comment by kevinfaveri** [comment]
It is not atomic, it creates multiple instructions and then sends multiple transactions. However, it does it all on a single signature, meaning the user will only receive a single popup (and not 5 if they are minting five). Since it generates X number of transactions (one for each NFT you want to mint), you can just listen to these transactions to check if they succeeded or failed.

**Comment by AlexLeung** [comment]
I noticed that Solflare throws a runtime error when trying to call `signAllTransactions` on the txns generated by your code.

**Comment by kevinfaveri** [comment]
Hey @AlexLeung yeah it might because it does not support big instructions. This is why this is a partial workaround right now, it does not change the fact that the candy machine could implement a program function for that

**Comment by AlexLeung** [comment]
All of a sudden started getting this error from Phantom.

```
Transaction failed: You cannot unilaterally verify another creator, they must sign
```

you seeing this too?

**Comment by devtimnbr** [comment]
> All of a sudden started getting this error from Phantom.
> 
> ```
> Transaction failed: You cannot unilaterally verify another creator, they must sign
> ```
> 
> you seeing this too?

Also got this error all of a sudden.

**Comment by AlexLeung** [comment]
I'm assuming Phantom pushed a new update that has an additional validation it once didn't

**Comment by lz2470** [comment]
did u guys fix the problem? I suddenly met same problem, after I mint 16 nfts

**Comment by AlexLeung** [comment]
![phantom-ticket](https://user-images.githubusercontent.com/5025138/135881585-e8734297-12e5-4af3-8e90-05da1fb5598a.png)

Perhaps a long-shot but I requested that Phantom roll-back to prevent adversely affecting the Solana NFT ecosystem. I don't have time to debug this right now. Please post if you guys figure it out.

**Comment by AlexLeung** [comment]
```
{
    "InstructionError": [
        4,
        {
            "Custom": 54
        }
    ]
}
```

there's actually a chance this is coming from Candy Machine itself

**Comment by AlexLeung** [comment]
#611 has this issue

Perhaps #609 is related

**Comment by AlexLeung** [comment]
fixed by https://github.com/metaplex-foundation/metaplex/pull/614

**Comment by AlexLeung** [comment]
I don't think the original purpose of the issue has been fixed. @jordansexton the issue and fix I mentioned was for an unrelated issue which I originally assumed was related to the temporary code fix which @kevinfaveri provided. Overall this issue is still open until the candy machine smart contract itself supports multiple mints per call.

**Comment by cdric** [comment]
Hey guys. I was able to add support for multiple mints at once (using a similar implementation to the one provided in the Next Candy machine - https://github.com/maxwellfortney/next-candy-machine). 

However, since this is sending 5x instructions per mint (5 for 1 mint, 10 for 2 mints, 15 for 3 mints, and so on) to the wallet provided. For some reason the Phantom wallet provide isn't able to compute the transaction cost once the number of instructions exceeds 2 mints (or ~10 instructions). As such the max number of mint I can offer to our users is 2. After that, they won't know how much will be taken from their wallet which is gonna raise a red flag more than anything else (even though the transaction would go through if they approve it). We just can't go live with this limitation.

Also, this seems to be a wallet-specific issue, as with Solflare, the wallet provider breaks down each mint transaction so the user can review that. 

From a high level, these are hacks IMHO that have obvious limitations (2 mint max). It would be great if the Metaplex team can provide a native implementation of multiple mints so we don't have to rely on these workarounds that aren't very stable.

Is the Metaplex team considering adding this future in the near future? 

Thanks!
