### ISSUE TITLE
Reveal nft after mint

### ISSUE THREAD

**Issue by skosito** [metaplex-foundation/metaplex#420]
Hey, I've been checking candy machine a bit, and have a question, I would like to reveal nfts after mint, and show placholders until then, something like this: https://opensea.io/collection/thealcabones
 Is there a way to achieve this with candy machine, or I would need to fork it and adapt program?
Basically would be nice to show some nft placeholder and update metadata after mint at some point. Is it better to upload to arweave at reveal time and update metadata with new url, or metadata can contain both placeholder and arweave url and just replace them at reveal time? 
Thanks!

**Comment by soualid** [comment]
You can use the `update_metadata_accounts` method to achieve that, you'll have to iterate through all your collectible tokens to update it on every single ones. 

I am working on a PR (https://github.com/metaplex-foundation/metaplex/pull/399) to handle metadatas derivated from a base template that will allow to achieve what you want in a less expansive way.

In the between, you'll find an example client in `spl-token-metadata-test-client` that you can use to demonstrate the update of a single token, that you can use it this way: 

```cargo run --bin spl-token-metadata-test-client update_metadata_accounts --mint 2tAFUxeuvKd6oHXeSZ1aTg8esjTejszhSNZtEjuxQaC4 --keypair {redacted} --name 'updated' --uri 'up_to_you'
```

**Comment by skosito** [comment]
@soualid Thank you very much for quick answer, this is awesome! I am a bit new to candy machine code and will check your changes to try and understand it. As far as i can tell your approach would require urls to contain nft index. I have couple of questions if you have some more time: 
- Does this work for arweave?
- How are your assets formatted, is it 0.png... n.png + only one json file for template, or something else?
- Would solution to my problem be to first use template with placeholder url for all, and then updating that template with i-based urls? Could you please provide a command for updating whole template so I can try out your solution quickly?

**Comment by soualid** [comment]
The template will replace the `{i}` string with the index of the minted token, I never used arweave yet but if you can define a prefix like you would do on IPFS, it should work.

Sorry, what I said about the update is wrong, the way it's implemented, since the information is denormalized at mint time, even with a template, you would have to update every single token manually. The template would only save you fees at mint time, not for a reveal phase.

In fact, I'm not 100% sure, but I don't think it's even feasable because each token lives with their own datas after they have ben minted, which is different from the way it is on Ethereum/EVM/ERC721.

To complete my first answer: either with or without this metadata thing, you will have to update every single token to change their metadatas, using `update_metadata_accounts` (you'll find an example of this in the `spl-token-metadata-test-client` program of this repository), you'll have to iterate through all the mints of your candymachine to achieve that.

**Comment by skosito** [comment]
@soualid yes that makes sense, since this is basically like separate erc-20 with supply of 1. Thanks for great help, really appreciate it!
