### ISSUE TITLE
Infinite Loading 

### ISSUE THREAD

**Issue by saraspaudel** [metaplex-foundation/metaplex#512]
I have an empty wallet and the loading animation shows forever.

<img width="993" alt="Screen Shot 2021-09-26 at 10 30 29 AM" src="https://user-images.githubusercontent.com/13654369/134814934-bffc2992-c971-4011-801b-f6fc8e66fd24.png">

**Comment by yogeshj25** [comment]
I am having a similar issue which has not been resolved:
https://github.com/metaplex-foundation/metaplex/issues/498

**Comment by danter83** [comment]
This should help
https://www.youtube.com/watch?v=XYQHcZTMesk&t=1s

**Comment by gundulawn** [comment]
Same problem. Loading........................

**Comment by BlopeetyBlop** [comment]
this infinite loop, can't find fix for it, the video above isn't available. anyone has a solution?

**Comment by deeplearn-art** [comment]
I wonder what was in that video...

**Comment by yogeshj25** [comment]
its been 3 months and we are still waiting for a solution. someone please help. the wait has been too long!

**Comment by jasonansellto** [comment]
same issue very long load times

**Comment by yogeshj25** [comment]
a reply by nicolas on metaplex discord. 
"The client js code is doing a websocket call to the blockchain. The call download about 300mo worth of data which is huge, given the fact you have to download it every time you refresh the page. They are downloading the whole history of the metaplex contract, ie all stores created. Since it gains a lot of popularity, this method does not work anymore, they have to filter the history to only get the revelant part somehow. It has been 3 months but the project started in June, so this is a very early work and it is normal it takes time. We are working on a custom solution on our end (my company), I hope Metaplex will fix it before us but who knows ... "

**Comment by TreeSol** [comment]
Same issue, Could somebody share solution? maybe remove from index page all this collections?

**Comment by makarbaderko** [comment]
Also infinite loading

**Comment by anibaljasin** [comment]
same here, keeps loading for a several minutes
