### ISSUE TITLE
Re-add the testing tools to the build path

### ISSUE THREAD

**Issue by praskoson** [metaplex-foundation/metaplex#54]
All 4 programs (metaplex, auction, token-vault, token-metadata) also include a test CLI tool, but these have been removed from the build path due to some version mismatches with spl-token. These aren't an issue anymore so they can be re-added to the build path and used as a different way of learning how the contracts work.

**Comment by scottbolasevich** [comment]
you sure those tests are still compatible For more information about an error, try `rustc --explain E0308`.
warning: `metaplex-token-vault-test-client` (bin "metaplex-token-vault-test-client") generated 73 warnings
error: could not compile `metaplex-token-vault-test-client` due to 23 previous errors; 73 warnings emitted
