### ISSUE TITLE
Cost to deploy program?

### ISSUE THREAD

**Issue by jinhongkuan** [metaplex-foundation/metaplex#598]
I was trying to deploy my own modified version of the candy machine program onto devnet, and found out that it took away 5 SOL from my balance. The gas cost seems to be negligible, so I am not quite sure where that amount went? (e.g. is it for paying rent). I am wondering if it'd cost as much to deploy onto mainnet as well.

**Comment by cdric** [comment]
Which command did you run?

**Comment by uaktags** [comment]
5SOL is what I saw as well.

**Comment by cdric** [comment]
Mmm that is concerning. When using candymachine on the devenv I can see my wallet being charged ~0.0024 SOL per image being uploaded. If you got deducted 5 SOL did you tried to upload like 20K+ images?

**Comment by jinhongkuan** [comment]
It was prior to me even running the upload command - just deploying the Rust contract

**Comment by uaktags** [comment]
@cdric this isn't concerning at all.
He was charged 5 SOL becuase he deployed a contract, not interacted with the public contract created and owned by Metaplex (prefix candy). He made edits to the candymachine SOL program, and deployed that and it cost him 5SOL.

You were charged ~0.0024 SOL per image being uploaded because thats the fee you're paying for the Arweave storage. That fee is separate from what's being discussed and is expected (based on the size of the media being uploaded to Arweave).

**Comment by cdric** [comment]
Thank you @uaktags for educating me. I am new to smart contracts, and my experience with the candy machine has been purely without smart contract modifications.

**Comment by jinhongkuan** [comment]
Should the contract itself cost that much?

**Comment by uaktags** [comment]
@jinhongkuan , 5SOL to deploy the entire contract? Yea it seems about right.
