### ISSUE TITLE
Error uploading file N Error: No transaction ID for upload: N

### ISSUE THREAD

**Issue by Giildev** [metaplex-foundation/metaplex#822]
I'm Getting this error:
> **Error uploading file 0 Error: No transaction ID for upload: 0**
 When Running `npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet.json`

**To Reproduce**

I have 10 images with it own json file, i.e:

```json
{
  "name": "X #0",
  "symbol": "X",
  "description": "X",
  "seller_fee_basis_points": 100,
  "image": "image.png",
  "external_url": "https://cryptoX.com",
  "edition": 0,
  "attributes": [
    {
      "trait_type": "att0",
      "value": "att0"
    },
    {
      "trait_type": "att1",
      "value": "att1"
    },
    {
      "trait_type": "att2",
      "value": "att2"
    },
    {
      "trait_type": "att3",
      "value": "att3"
    }
  ],
  "properties": {
    "files": [
      {
        "uri": "image.png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "address": "XXXXXXXXXXX",
        "share": 50
      },
      {
        "address": "XXXXXXXXXX",
        "share": 25
      },
      {
        "address": "XXXXXXXXXX",
        "share": 25
      }
    ]
  }
}
```

Run `npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet.json`
Output:
```zsh
npx ts-node js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet.json
Beginning the upload for 10 (png+json) pairs
started at: 1635443651905
wallet public key: XXXXXXXXXXXXXXX
Processing file: 0
Total bytes 24158
txn fee 1355904
byte cost 11560243
total ar 0.000012916147
Calling conversion rate
Ar mult 0.24379164142943668
storage cost of assets\0.png: 3463.733545881284
Error uploading file 0 Error: No transaction ID for upload: 0
    at Object.<anonymous> (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:180:11)
    at step (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:52:23)
    at Object.next (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:33:53)
    at fulfilled (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Total bytes 14241
txn fee 1355904
byte cost 7371302
total ar 0.000008727206
Calling conversion rate
Ar mult 0.24379164142943668
storage cost of assets\1.png: 2340.381863416111
```

**Expected behavior**
Upload file to my wallet

**Desktop:**
 - Windows 11
 - Chrome

**Comment by ReDey3** [comment]
seeing this error again...

**Comment by triiq** [comment]
> seeing this error again... Error uploading file 116 Error: No transaction ID for upload: 116 at Object. (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:116:11) at step (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:52:23) at Object.next (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:33:53) at fulfilled (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:24:58) at runMicrotasks ()
 
Did you ever figure this out?

**Comment by Luxroy** [comment]
> > seeing this error again... Error uploading file 116 Error: No transaction ID for upload: 116 at Object. (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:116:11) at step (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:52:23) at Object.next (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:33:53) at fulfilled (X\metaplex\js\packages\cli\src\helpers\upload\arweave.ts:24:58) at runMicrotasks ()
> 
> Did you ever figure this out?

To the best of my knowledge this is an issue with Arweave, there's a part of the code in the arweave upload helper that throws this generic error if arweave for whatever reason couldn't upload your file.

**The workaround i found for this was to use another one of the uploaders that are available, in this instance IPFS**, as it achieves exactly the same purpose as arweave.

To use IPFS instead of arweave (default), you just have to modify the CLI command a bit.

It is very important to mention that IPFS requires some setting up, which you can do on this link for free: https://infura.io/docs/ipfs , after setting up your IPFS infura project, you'll have an IPFS project ID and an IPFS secret key.

Try the following CLI command after setting up your IPFS project: `ts-node <path-to-candy-machine.ts> upload -e mainnet-beta -k yourkeypair.json -s ipfs --ipfs-infura-project-id <your-ipfs-id-project-id> --ipfs-infura-secret <your-ipfs-secret-key>`

If succesful, your metadata will have been uploaded to IPFS instead of arweave, and your temp file should look something like this (The onChain paremeter being true indicates success):

![image](https://user-images.githubusercontent.com/57853508/142019149-7c0927d8-96e0-42ed-b89a-b9624b618a20.png)

**Comment by verata-veritatis** [comment]
Coming across this issue at the moment when uploading a set of 5,000 assets. I have about 20 of them that failed. Is there any way to re-attempt? I'm assuming once you upload assets to IPFS manually you can simply add the link yourself in the temp file. Not sure though...

**Comment by yusufozcan** [comment]
using `--branch v1.0.0` solved for me

`git clone --branch v1.0.0 https://github.com/metaplex-foundation/metaplex.git
`

**Comment by MosaabSupa** [comment]
> For what its worth, i have the same issue, cloned the entire repository from scratch, and still getting the same issue.
> 
> This is the piece of code throwing the error on the metaplex/js/packages/cli/src/helpers/upload/arweave.ts path: ![image](https://user-images.githubusercontent.com/57853508/139371073-e5263cc1-467d-4182-bff0-511ec53e8c41.png)
> 
> I am on Windows 10 though. solana-cli 1.8.0.

Add dna:"<generated_number>" to each json file related to the pictures in assets folder.

**Comment by drahul540** [comment]
check your -c location.
