### ISSUE TITLE
Creating NFT collection with symbol of existing SPL token should be prohibited

### ISSUE THREAD

**Issue by wimdows-nl** [metaplex-foundation/metaplex#868]
**Describe the bug**
Currently, it looks like any malicious actor can create an NFT collection and use the symbol of an existing SPL token to hijack the Solana Explorer view or Solscan view.

It might be in combination with a revoked owner (null) on the original SPL token.

See our messed up SPL token here:

https://explorer.solana.com/address/8ymi88q5DtmdNTn2sPRNFkvMkszMHuLJ1e3RVdWjPa3s

Screen grab:
<img width="1192" alt="Untitled" src="https://user-images.githubusercontent.com/24444562/139727827-41b46f94-b23b-4669-8cf7-e469b1b9ea91.png">

The meta data that comes back in Solana Explorer looks like this:

![meta](https://user-images.githubusercontent.com/24444562/139727710-5d8a0080-de24-4198-8768-9f677abf5615.png)

This clearly messes up the existing SPL token that was there and causes issues when people verify the contract address and other SPL token details.

Solution: Prevent NFT collections to have a an NFT code/symbol that already exists in the SPL token list.

**Comment by scara89** [comment]
Hi Wim ! Seems this issue is an other. According to @aheckmann , they did a massive update that may broke your token Check that comment related with this update authority adress: https://github.com/metaplex-foundation/metaplex/issues/1055#issuecomment-985838251

AqH29mZfQFgRpfwaPoTMWSKJ5kqauoc1FwVBRksZyQrt
